version: '3'

services:
  postgres:
    image: postgres:16.1-bookworm
    container_name: mypostgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - /var/postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:7.2-bookworm"
    container_name: "myredis"
    ports:
      - "6379:6379"
    volumes:
      - /var/redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]