package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"app/graph/generated"
	"app/pkg/db/models"
	passwordPkg "app/pkg/password"
	"context"
	"errors"
	"fmt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*generated.AuthPayload, error) {

	user := &models.User{}

	result := r.Db.Where("email = ?", email).First(&user)

	if result.Error != nil {
		fmt.Println(result.Error)
		return nil, result.Error
	}

	err := passwordPkg.ComparePassword(password, user.Password)

	if err != nil {
		return nil, errors.New("password does not match")
	}

	response := &generated.AuthPayload{
		Token: "some-token",
		User:  models.DBUserToGraphUser(user),
	}

	return response, nil
}
